# ----------------------- #
#     Site Variables      #
# ----------------------- #

name: Andreas Renberg (IQAndreas)
author: Andreas Renberg (IQAndreas)
url: 'http://www.iqandreas.com/github-issues-import/'

title: "GitHub Issues Importer"
subtitle: "Python script to import issues from one repository into another, either one at a time or all of them at once"

github_url: https://github.com/IQAndreas/github-issues-import/
github_username: IQAndreas

#copyright_message: &copy;&nbsp;2014 by Andreas&nbsp;Renberg
github_license: The MIT License
github_license_url: https://github.com/IQAndreas/markdown-licenses/blob/master/mit.md


# ----------------------- #
#       Site Paths        #
# ----------------------- #

# LOCAL
stylesheets: /assets/stylesheets
javascripts: /assets/javascripts
images:      /assets/images
fonts:       /assets/fonts

# GLOBAL
global_stylesheets: http://static.iqandreas.com/assets/stylesheets
global_javascripts: http://static.iqandreas.com/assets/javascripts
global_images:      http://static.iqandreas.com/assets/images
global_fonts:       http://static.iqandreas.com/assets/fonts

# ----------------------- #
#     Plugin Configs      #
# ----------------------- #

google_analytics_id:   UA-44446017-1
google_analytics_name: iqandreas.com

source_title_prefix: "GitHub: IQAndreas/github-issues-import"
source_url: 'https://github.com/IQAndreas/github-issues-import/tree/gh-pages'

# ----------------------- #
#     Jekyll Configs      #
# ----------------------- #

#source: source
destination: _public
plugins: 	 _plugins

exclude: [LICENSE.md, update.sh]

relative_permalinks: false
markdown: redcarpet
pygments: true

